In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
IMAGE_SIZE = 256
CHANNELS = 3

In [3]:
train_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True
)
train_generator = train_datagen.flow_from_directory(
        'dataset/train',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse",
#         save_to_dir="C:\\Code\\potato-disease-classification\\training\\AugmentedImages"
)

Found 1506 images belonging to 3 classes.


In [4]:
train_generator.class_indices

{'Potato___Early_blight': 0, 'Potato___Late_blight': 1, 'Potato___healthy': 2}

In [5]:
class_names = list(train_generator.class_indices.keys())
class_names

['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']

In [6]:
count=0
for image_batch, label_batch in train_generator:
#     print(label_batch)
    print(image_batch[0])
    break
#     count+=1
#     if count>2:
# 

[[[0.5786883  0.55123734 0.5786883 ]
  [0.57985765 0.55240667 0.57985765]
  [0.5810269  0.55357593 0.5810269 ]
  ...
  [0.5349499  0.5074989  0.53887147]
  [0.522134   0.49468303 0.5260556 ]
  [0.52604467 0.4985937  0.52996624]]

 [[0.56304574 0.53559476 0.56304574]
  [0.564215   0.536764   0.564215  ]
  [0.56538427 0.5379333  0.56538427]
  ...
  [0.53378063 0.50632966 0.5377022 ]
  [0.5224263  0.49497533 0.5263479 ]
  [0.526337   0.498886   0.5302586 ]]

 [[0.5741656  0.5467146  0.5741656 ]
  [0.5729963  0.54554534 0.5729963 ]
  [0.57182705 0.5443761  0.57182705]
  ...
  [0.53261137 0.5051604  0.53653294]
  [0.5227186  0.49526766 0.5266402 ]
  [0.5266293  0.4991783  0.5305509 ]]

 ...

 [[0.47742268 0.4499717  0.48134425]
  [0.47058827 0.4431373  0.47450984]
  [0.4788703  0.45141932 0.48279187]
  ...
  [0.4168472  0.3933178  0.44821975]
  [0.4165549  0.39302546 0.44792745]
  [0.41626254 0.39273313 0.44763508]]

 [[0.4756688  0.4482178  0.47959036]
  [0.47058827 0.4431373  0.47450984]


In [7]:
validation_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)
validation_generator = validation_datagen.flow_from_directory(
        'dataset/val',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 215 images belonging to 3 classes.


In [8]:
test_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)

test_generator = test_datagen.flow_from_directory(
        'dataset/test',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 431 images belonging to 3 classes.


In [9]:
for image_batch, label_batch in test_generator:
    print(image_batch[0])
    break

[[[0.78168494 0.7620771  0.7856065 ]
  [0.76988024 0.7502724  0.7738018 ]
  [0.7594516  0.7398438  0.7633732 ]
  ...
  [0.56882733 0.54137635 0.56882733]
  [0.5672828  0.5398318  0.5672828 ]
  [0.5657383  0.53828734 0.5657383 ]]

 [[0.78176624 0.7621584  0.7856878 ]
  [0.7702054  0.75059754 0.77412695]
  [0.7596142  0.7400064  0.7635358 ]
  ...
  [0.6545858  0.6271348  0.6545858 ]
  [0.65832514 0.63087416 0.65832514]
  [0.66206455 0.6346136  0.66206455]]

 [[0.78184754 0.7622397  0.7857691 ]
  [0.7705305  0.7509227  0.7744521 ]
  [0.7597768  0.7401689  0.76369834]
  ...
  [0.65502506 0.6275741  0.65502506]
  [0.6528303  0.62537926 0.6528303 ]
  [0.6506354  0.62318444 0.6506354 ]]

 ...

 [[0.6759193  0.6641546  0.70729184]
  [0.67526895 0.66350424 0.7066415 ]
  [0.6746186  0.6628539  0.7059912 ]
  ...
  [0.58677834 0.56324893 0.6024646 ]
  [0.5755769  0.5520475  0.5941754 ]
  [0.5491419  0.5256125  0.5726713 ]]

 [[0.65360844 0.64184374 0.684981  ]
  [0.65352714 0.64176244 0.6848997 ]


In [10]:
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 3

model = models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32, kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 127, 127, 32)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 62, 62, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 30, 30, 64)       0

In [12]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [13]:
1506/32

47.0625

In [14]:
215/32

6.71875

In [15]:
history = model.fit(
    train_generator,
    steps_per_epoch=47,
    batch_size=32,
    validation_data=validation_generator,
    validation_steps=6,
    verbose=1,
    epochs=20,
)

Epoch 1/20
47/47 [==============================] - 884s 19s/step - loss: 0.9049 - accuracy: 0.4769 - val_loss: 0.8772 - val_accuracy: 0.6510
Epoch 2/20
47/47 [==============================] - 789s 17s/step - loss: 0.7341 - accuracy: 0.7076 - val_loss: 0.7398 - val_accuracy: 0.6250
Epoch 3/20
47/47 [==============================] - 1077s 23s/step - loss: 0.4942 - accuracy: 0.7931 - val_loss: 0.3258 - val_accuracy: 0.8333
Epoch 4/20
47/47 [==============================] - 865s 18s/step - loss: 0.3309 - accuracy: 0.8752 - val_loss: 0.3422 - val_accuracy: 0.8542
Epoch 5/20
47/47 [==============================] - 977s 21s/step - loss: 0.2947 - accuracy: 0.8792 - val_loss: 0.3199 - val_accuracy: 0.8698
Epoch 6/20
47/47 [==============================] - 1037s 22s/step - loss: 0.2295 - accuracy: 0.9118 - val_loss: 0.2785 - val_accuracy: 0.8958
Epoch 7/20
47/47 [==============================] - 968s 21s/step - loss: 0.2038 - accuracy: 0.9172 - val_loss: 0.2929 - val_accuracy: 0.8802
Epoc